// ═══════════════════════════════════════════════════════════
// GEMINIGEN AUTO FLOW PRO - Background Service Worker v2.0
// ═══════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════
// DATABASE - Memory System (come Whisk)
// ═══════════════════════════════════════════════════════════

const DB = {
  characters: {},
  environments: {},
  scripts: {},          // Copioni completi
  projects: {},         // Progetti di lavoro
  activeProject: null,
  autoGeneratedCharacter: null,  // Personaggio auto-generato
  autoGeneratedEnvironment: null // Ambiente auto-generato
};

// ═══════════════════════════════════════════════════════════
// AUTO GENERATE FUNCTION
// ═══════════════════════════════════════════════════════════

function autoGenerateFromScript(scenes) {
  const result = {
    character: null,
    environment: null,
    autoGenerated: false
  };
  
  // Genera personaggio se non presente
  if (!DB.autoGeneratedCharacter) {
    result.character = AutoGenerator.generateCharacterFromScript(scenes);
    DB.autoGeneratedCharacter = result.character;
    DB.characters[result.character.id] = result.character;
  } else {
    result.character = DB.autoGeneratedCharacter;
  }
  
  // Genera ambiente se non presente
  if (!DB.autoGeneratedEnvironment) {
    result.environment = AutoGenerator.generateEnvironmentFromScript(scenes);
    DB.autoGeneratedEnvironment = result.environment;
    DB.environments[result.environment.id] = result.environment;
  } else {
    result.environment = DB.autoGeneratedEnvironment;
  }
  
  result.autoGenerated = true;
  
  // Salva
  saveDB();
  
  console.log('[AutoGenerate] Character:', result.character.name);
  console.log('[AutoGenerate] Environment:', result.environment.name);
  
  return { success: true, ...result };
}

// Reset auto-generated (quando utente seleziona manualmente)
function resetAutoGenerated() {
  DB.autoGeneratedCharacter = null;
  DB.autoGeneratedEnvironment = null;
  saveDB();
}

// ═══════════════════════════════════════════════════════════
// SCRIPT PARSER - Suddivide copione in scene/prompt
// ═══════════════════════════════════════════════════════════

const ScriptParser = {
  // SepARATORI per dividere il copione in scene
  separators: [
    /\n\n+/,                    // Paragrafi vuoti
    /\[SCENA\s*\d*\]/i,         // [SCENA 1], [SCENA]
    /SCENE\s*\d*:/i,           // SCENE 1:
    /---\s*/,                   // ---
    /\*+\s*/,                   // ***
    /\.\.\.\s*/,               // ...
    /\n(?=[A-Z][a-z]+:)/m       // PERSONAGGIO: (dialogo)
  ],
  
  // Parse copione in scene
  parseScript(text) {
    const scenes = [];
    const lines = text.split('\n').filter(l => l.trim());
    
    let currentScene = {
      index: 0,
      title: '',
      prompts: [],
      duration: 6,
      character: null,
      environment: null
    };
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      
      // Rileva nuovo titolo scena
      if (/^(SCENA|SCENE|ACT|PARTE|PART)/i.test(line) || 
          /^\d+[\.\)]\s*/.test(line) ||
          /^\[.+\]/.test(line)) {
        
        if (currentScene.prompts.length > 0 || currentScene.title) {
          scenes.push({...currentScene});
        }
        
        currentScene = {
          index: scenes.length,
          title: line.replace(/^\[|\]$/g, '').trim(),
          prompts: [],
          duration: 6,
          character: null,
          environment: null
        };
      }
      // Altrimenti aggiungi come prompt
      else if (line.length > 5) {
        currentScene.prompts.push(line);
      }
    }
    
    // Aggiungi ultima scena
    if (currentScene.prompts.length > 0 || currentScene.title) {
      scenes.push({...currentScene});
    }
    
    // Se non ci sono scene, crea una singola con tutto
    if (scenes.length === 0 && text.trim()) {
      scenes.push({
        index: 0,
        title: 'Scena Unica',
        prompts: [text.trim()],
        duration: 6,
        character: null,
        environment: null
      });
    }
    
    return scenes;
  },
  
  // Combina scene per clip lunga
  combineForLongClip(scenes, targetDuration) {
    const combined = [];
    let currentGroup = [];
    let currentDuration = 0;
    const clipsPerGroup = Math.ceil(targetDuration / 6);
    
    for (const scene of scenes) {
      currentGroup.push(scene);
      
      if (currentGroup.length >= clipsPerGroup) {
        combined.push({
          scenes: [...currentGroup],
          prompt: this.buildCombinedPrompt(currentGroup),
          duration: Math.min(targetDuration, currentGroup.length * 6)
        });
        currentGroup = [];
      }
    }
    
    // Aggiungi gruppi rimanenti
    if (currentGroup.length > 0) {
      combined.push({
        scenes: [...currentGroup],
        prompt: this.buildCombinedPrompt(currentGroup),
        duration: currentGroup.length * 6
      });
    }
    
    return combined;
  },
  
  // Costruisce prompt combinato da scene
  buildCombinedPrompt(scenes) {
    return scenes.map(s => {
      const titlePart = s.title ? `[${s.title}] ` : '';
      return titlePart + s.prompts.join(' ');
    }).join(' | ');
  }
};

// ═══════════════════════════════════════════════════════════
// CLIP INTELLIGENCE ENGINE
// ═══════════════════════════════════════════════════════════

const ClipEngine = {
  // Formati clip supportati
  formats: {
    micro: 4,    // 4 secondi
    short: 6,    // 6 secondi
    medium: 8,   // 8 secondi
    long: 15,    // 15 secondi
    full: 30     // 30 secondi
  },
  
  // Decisione automatica clip
  decideClipFormat(sceneCount, targetDuration) {
    // Se target è 30s e abbiamo 5 scene da 6s, combiniamo
    if (targetDuration === 30 && sceneCount > 1) {
      const groups = Math.ceil(sceneCount / 5);
      return {
        clipDuration: 6,
        scenesPerClip: Math.ceil(sceneCount / groups),
        totalClips: groups,
        mode: 'combined_30s'
      };
    }
    
    // Altrimenti clip singola
    return {
      clipDuration: targetDuration,
      scenesPerClip: 1,
      totalClips: sceneCount,
      mode: 'single'
    };
  },
  
  // Genera sequenza di clip da copione
  generateClipSequence(scenes, options = {}) {
    const { targetDuration = 6, autoCombine = true } = options;
    
    // Se autoCombine e target è lungo
    if (autoCombine && targetDuration >= 15 && scenes.length > 1) {
      return this.combineForLongClip(scenes, targetDuration);
    }
    
    // Altrimenti una clip per scena
    return scenes.map((scene, i) => ({
      index: i,
      scene: scene,
      prompt: scene.prompts.join(' '),
      duration: Math.min(targetDuration, scene.duration || 6),
      startTime: i * (scene.duration || 6)
    }));
  },
  
  // Combina scene per clip lunga
  combineForLongClip(scenes, targetDuration) {
    const clips = [];
    const scenesPerClip = Math.ceil(scenes.length / Math.ceil(targetDuration / 6));
    
    for (let i = 0; i < scenes.length; i += scenesPerClip) {
      const group = scenes.slice(i, i + scenesPerClip);
      clips.push({
        index: clips.length,
        scenes: group,
        prompt: group.map(s => `[${s.title || 'S' + s.index}] ${s.prompts.join(' ')}`).join(' '),
        duration: Math.min(targetDuration, group.length * 6),
        sceneRange: `${i + 1}-${Math.min(i + scenesPerClip, scenes.length)}`
      });
    }
    
    return clips;
  }
};

// ═══════════════════════════════════════════════════════════
// AUTO GENERATOR - Genera personaggi/ambienti se mancanti
// ═══════════════════════════════════════════════════════════

const AutoGenerator = {
  // Genera personaggio da copione/scene
  generateCharacterFromScript(scenes) {
    // Analizza il copione per identificare personaggi
    const allText = scenes.map(s => s.title + ' ' + s.prompts.join(' ')).join(' ');
    
    // Pattern comuni per identificare personaggi
    const patterns = [
      /(?:un|uomo|una|donna|bambino|bambina|ragazzo|ragazza|personaggio|protagonista|antagonista|eroe|villano)\s*(?:di\s+)?([^,\.]+)/i,
      /([A-Z][a-z]+)\s+(?:entra|esce|appare|scompare|cammina|corre|grida|parla)/,
      /([A-Z][a-z]+):\s*(.+)/,
      /(?:il|l'|la)\s+([a-z]+)\s+(?:è|ha|sembra)/i
    ];
    
    let characterName = null;
    let characterDesc = null;
    
    for (const pattern of patterns) {
      const match = allText.match(pattern);
      if (match) {
        characterName = match[1] || match[2] || 'Protagonista';
        characterDesc = this.extractCharacterDescription(allText, characterName);
        break;
      }
    }
    
    if (!characterName) {
      // Genera personaggio generico basato sul tono del copione
      const tone = this.detectTone(scenes);
      characterName = tone.defaultCharacter;
      characterDesc = tone.defaultDesc;
    }
    
    return {
      id: 'auto_char_' + Date.now(),
      name: characterName,
      description: characterDesc,
      prompt: this.buildCharacterPrompt(characterName, characterDesc),
      autoGenerated: true,
      createdAt: Date.now()
    };
  },
  
  // Genera ambiente da copione/scene
  generateEnvironmentFromScript(scenes) {
    const allText = scenes.map(s => s.title + ' ' + s.prompts.join(' ')).join(' ');
    
    // Pattern per ambienti
    const patterns = [
      /(?:in|nel|alla|nella)\s+([^,\.]+)/i,
      /(?:dentro|dentro\s+a)\s+([^,\.]+)/i,
      /(?:luogo|posto|location|scenario):\s*([^,\.]+)/i,
      /(?:accade|avviene|svolge)\s+(?:in|al)\s+([^,\.]+)/i
    ];
    
    let envName = null;
    let envDesc = null;
    let envMood = 'neutral';
    let envLighting = 'natural';
    
    for (const pattern of patterns) {
      const match = allText.match(pattern);
      if (match && match[1].length > 2) {
        envName = match[1].trim();
        envDesc = this.extractEnvironmentDescription(allText, envName);
        break;
      }
    }
    
    if (!envName) {
      const tone = this.detectTone(scenes);
      envName = tone.defaultEnvironment;
      envDesc = tone.defaultEnvDesc;
      envMood = tone.mood;
      envLighting = tone.lighting;
    }
    
    return {
      id: 'auto_env_' + Date.now(),
      name: envName,
      description: envDesc,
      mood: envMood,
      lighting: envLighting,
      autoGenerated: true,
      createdAt: Date.now()
    };
  },
  
  // Estrai descrizione personaggio
  extractCharacterDescription(text, name) {
    const sentences = text.split(/[.!]/);
    for (const sentence of sentences) {
      if (sentence.toLowerCase().includes(name.toLowerCase())) {
        // Estrai descrizione dalla frase
        const desc = sentence.trim();
        if (desc.length > 10 && desc.length < 200) {
          return desc;
        }
      }
    }
    return this.generateGenericDescription(text);
  },
  
  // Genera descrizione generica
  generateGenericDescription(text) {
    const hasDark = /dark|notte|oscur|tenebr/i.test(text);
    const hasAction = /esplos|azion|cors|combatt/i.test(text);
    const hasSciFi = /spaz|alien|robot|tecnolog/i.test(text);
    
    if (hasSciFi) return 'A mysterious figure with futuristic attire';
    if (hasAction) return 'An athletic person in dynamic pose';
    if (hasDark) return 'A shadowy silhouette in dark atmosphere';
    return 'A person with cinematic presence';
  },
  
  // Estrai descrizione ambiente
  extractEnvironmentDescription(text, name) {
    const sentences = text.split(/[.!]/);
    for (const sentence of sentences) {
      if (sentence.toLowerCase().includes(name.toLowerCase())) {
        const desc = sentence.trim();
        if (desc.length > 10 && desc.length < 200) {
          return desc;
        }
      }
    }
    return `Location: ${name}. Cinematic setting.`;
  },
  
  // Costruisci prompt personaggio
  buildCharacterPrompt(name, description) {
    return `${name}. ${description}. Cinematic style, detailed, high quality rendering.`;
  },
  
  // Rileva tono del copione
  detectTone(scenes) {
    const allText = scenes.map(s => s.prompts.join(' ')).join(' ').toLowerCase();
    
    if (/alien|spaz|galax|rocket|astro/i.test(allText)) {
      return {
        mood: 'mysterious',
        lighting: 'dramatic neon',
        defaultCharacter: 'Astronaut',
        defaultDesc: 'A space explorer in futuristic suit',
        defaultEnvironment: 'Space Station',
        defaultEnvDesc: 'Futuristic space station with neon lights and control panels'
      };
    }
    
    if (/uffici|azienda|reunion|computer/i.test(allText)) {
      return {
        mood: 'professional',
        lighting: 'office fluorescent',
        defaultCharacter: 'Business Person',
        defaultDesc: 'A professional in smart casual attire',
        defaultEnvironment: 'Office',
        defaultEnvDesc: 'Modern office with desks and computers'
      };
    }
    
    if (/foresta|alber|natura|selvag/i.test(allText)) {
      return {
        mood: 'serene',
        lighting: 'natural sunlight',
        defaultCharacter: 'Wanderer',
        defaultDesc: 'A traveler in outdoor clothing',
        defaultEnvironment: 'Forest',
        defaultEnvDesc: 'Dense forest with sunlight filtering through trees'
      };
    }
    
    // Default cinematic
    return {
      mood: 'dramatic',
      lighting: 'cinematic',
      defaultCharacter: 'Mysterious Figure',
      defaultDesc: 'A silhouetted person in dramatic lighting',
      defaultEnvironment: 'Cinematic Scene',
      defaultEnvDesc: 'Dramatic setting with cinematic lighting and atmosphere'
    };
  }
};

// ═══════════════════════════════════════════════════════════
// GENERATIONS TRACKER - Quote e limiti
// ═══════════════════════════════════════════════════════════

const QuotaTracker = {
  quota: {
    daily: { total: 0, used: 0, remaining: 0 },
    monthly: { total: 0, used: 0, remaining: 0 },
    unlimited: false
  },
  
  update(data) {
    this.quota = { ...this.quota, ...data };
    this.save();
    this.broadcast();
  },
  
  recordGeneration(success) {
    if (!this.quota.unlimited) {
      this.quota.daily.used++;
      this.quota.monthly.used++;
      this.quota.daily.remaining = Math.max(0, this.quota.daily.total - this.quota.daily.used);
      this.quota.monthly.remaining = Math.max(0, this.quota.monthly.total - this.quota.monthly.used);
    }
    this.save();
    this.broadcast();
  },
  
  canGenerate() {
    if (this.quota.unlimited) return { allowed: true };
    return {
      allowed: this.quota.daily.remaining > 0,
      remaining: this.quota.daily.remaining
    };
  },
  
  getDisplay() {
    if (this.quota.unlimited) {
      return { status: 'unlimited', daily: '∞', monthly: '∞', remaining: '∞' };
    }
    return {
      status: this.quota.daily.remaining > 0 ? 'active' : 'depleted',
      daily: { used: this.quota.daily.used, total: this.quota.daily.total },
      monthly: { used: this.quota.monthly.used, total: this.quota.monthly.total },
      remaining: this.quota.daily.remaining
    };
  },
  
  async save() {
    await chrome.storage.local.set({ quota: this.quota });
  },
  
  async load() {
    const result = await chrome.storage.local.get('quota');
    if (result.quota) this.quota = result.quota;
  },
  
  broadcast() {
    chrome.runtime.sendMessage({ type: 'QUOTA_UPDATE', quota: this.getDisplay() }).catch(() => {});
  }
};

// ═══════════════════════════════════════════════════════════
// AUTO FLOW STATE
// ═══════════════════════════════════════════════════════════

const AutoFlow = {
  isRunning: false,
  isPaused: false,
  currentClipIndex: 0,
  clips: [],
  config: {
    clipDuration: 6,
    autoCombine: true,
    delayBetween: 2000,
    contextMode: 'character' // 'character' | 'environment' | 'both'
  },
  
  start(clips, config = {}) {
    this.clips = clips;
    this.config = { ...this.config, ...config };
    this.isRunning = true;
    this.isPaused = false;
    this.currentClipIndex = 0;
    this.broadcast();
  },
  
  pause() {
    this.isPaused = true;
    this.broadcast();
  },
  
  resume() {
    this.isPaused = false;
    this.broadcast();
  },
  
  stop() {
    this.isRunning = false;
    this.isPaused = false;
    this.broadcast();
  },
  
  nextClip() {
    this.currentClipIndex++;
    if (this.currentClipIndex >= this.clips.length) {
      this.stop();
    }
    this.broadcast();
  },
  
  getCurrentClip() {
    return this.clips[this.currentClipIndex];
  },
  
  getProgress() {
    return {
      current: this.currentClipIndex + 1,
      total: this.clips.length,
      percentage: Math.round(((this.currentClipIndex + 1) / this.clips.length) * 100),
      clip: this.getCurrentClip()
    };
  },
  
  broadcast() {
    chrome.runtime.sendMessage({ 
      type: 'FLOW_UPDATE', 
      flow: { isRunning: this.isRunning, isPaused: this.isPaused },
      progress: this.getProgress()
    }).catch(() => {});
  }
};

// ═══════════════════════════════════════════════════════════
// MESSAGE HANDLER
// ═══════════════════════════════════════════════════════════

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  console.log('[Background] Message:', msg.type);
  
  switch (msg.type) {
    // === CHARACTER ===
    case 'SAVE_CHARACTER':
      saveCharacter(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'GET_CHARACTERS':
      sendResponse({ success: true, characters: DB.characters });
      return true;
      
    case 'DELETE_CHARACTER':
      deleteCharacter(msg.id).then(r => sendResponse(r));
      return true;
      
    // === ENVIRONMENT ===
    case 'SAVE_ENVIRONMENT':
      saveEnvironment(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'GET_ENVIRONMENTS':
      sendResponse({ success: true, environments: DB.environments });
      return true;
      
    case 'DELETE_ENVIRONMENT':
      deleteEnvironment(msg.id).then(r => sendResponse(r));
      return true;
      
    // === SCRIPT ===
    case 'LOAD_SCRIPT':
      loadScript(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'PARSE_SCRIPT':
      const scenes = ScriptParser.parseScript(msg.text);
      sendResponse({ success: true, scenes });
      return true;
      
    case 'GENERATE_CLIP_SEQUENCE':
      const clips = ClipEngine.generateClipSequence(msg.scenes, msg.options);
      sendResponse({ success: true, clips });
      return true;
      
    case 'SAVE_SCRIPT':
      saveScript(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'GET_SCRIPTS':
      sendResponse({ success: true, scripts: DB.scripts });
      return true;
      
    // === AUTO FLOW ===
    case 'START_FLOW':
      AutoFlow.start(msg.clips, msg.config);
      sendResponse({ success: true });
      return true;
      
    case 'PAUSE_FLOW':
      AutoFlow.pause();
      sendResponse({ success: true });
      return true;
      
    case 'RESUME_FLOW':
      AutoFlow.resume();
      sendResponse({ success: true });
      return true;
      
    case 'STOP_FLOW':
      AutoFlow.stop();
      sendResponse({ success: true });
      return true;
      
    case 'GET_FLOW_STATUS':
      sendResponse({ success: true, flow: AutoFlow, progress: AutoFlow.getProgress() });
      return true;
      
    case 'NEXT_CLIP':
      AutoFlow.nextClip();
      sendResponse({ success: true, clip: AutoFlow.getCurrentClip() });
      return true;
      
    // === QUOTA ===
    case 'UPDATE_QUOTA':
      QuotaTracker.update(msg.data);
      sendResponse({ success: true });
      return true;
      
    case 'GET_QUOTA':
      sendResponse({ success: true, quota: QuotaTracker.getDisplay() });
      return true;
      
    case 'RECORD_GENERATION':
      QuotaTracker.recordGeneration(msg.success);
      sendResponse({ success: true, canGenerate: QuotaTracker.canGenerate() });
      return true;
      
    // === CONFIG ===
    case 'GET_CONFIG':
      sendResponse({ success: true, config: AutoFlow.config });
      return true;
      
    case 'SET_CONFIG':
      AutoFlow.config = { ...AutoFlow.config, ...msg.config };
      saveConfig();
      sendResponse({ success: true });
      return true;
      
    // === AUTO GENERATE ===
    case 'AUTO_GENERATE_MISSING':
      const result = autoGenerateFromScript(msg.scenes);
      sendResponse(result);
      return true;
      
    case 'GET_AUTO_GENERATED':
      sendResponse({ 
        success: true, 
        autoCharacter: DB.autoGeneratedCharacter,
        autoEnvironment: DB.autoGeneratedEnvironment 
      });
      return true;
      
    default:
      sendResponse({ success: false, error: 'Unknown type' });
  }
});

// ═══════════════════════════════════════════════════════════
// CRUD OPERATIONS
// ═══════════════════════════════════════════════════════════

async function saveCharacter(data) {
  const id = data.id || 'char_' + Date.now();
  DB.characters[id] = { id, ...data, createdAt: Date.now(), usageCount: 0 };
  await saveDB();
  return { success: true, id };
}

async function deleteCharacter(id) {
  delete DB.characters[id];
  await saveDB();
  return { success: true };
}

async function saveEnvironment(data) {
  const id = data.id || 'env_' + Date.now();
  DB.environments[id] = { id, ...data, createdAt: Date.now(), usageCount: 0 };
  await saveDB();
  return { success: true, id };
}

async function deleteEnvironment(id) {
  delete DB.environments[id];
  await saveDB();
  return { success: true };
}

async function saveScript(data) {
  const id = data.id || 'script_' + Date.now();
  const parsed = ScriptParser.parseScript(data.text);
  DB.scripts[id] = { id, name: data.name, text: data.text, scenes: parsed, createdAt: Date.now() };
  await saveDB();
  return { success: true, id, scenes: parsed };
}

async function loadScript(id) {
  const script = DB.scripts[id];
  if (!script) return { success: false, error: 'Not found' };
  return { success: true, script, scenes: script.scenes };
}

async function saveConfig() {
  await chrome.storage.local.set({ 
    config: AutoFlow.config,
    db: DB
  });
}

async function saveDB() {
  await chrome.storage.local.set({ db: DB });
}

async function loadDB() {
  const result = await chrome.storage.local.get(['db', 'quota', 'config']);
  if (result.db) {
    DB.characters = result.db.characters || {};
    DB.environments = result.db.environments || {};
    DB.scripts = result.db.scripts || {};
    DB.projects = result.db.projects || {};
  }
  if (result.quota) QuotaTracker.quota = result.quota;
  if (result.config) AutoFlow.config = result.config;
}

// ═══════════════════════════════════════════════════════════
// OUTPUT FOLDER SYSTEM
// ═══════════════════════════════════════════════════════════

const OutputFolder = {
  base: 'GeminiGen-AutoFlow',
  
  structure: {
    scripts: '01_Scripts',
    characters: '02_Characters',
    environments: '03_Environments',
    clips_6s: '04_Clips_6s',
    clips_8s: '05_Clips_8s',
    clips_15s: '06_Clips_15s',
    clips_30s: '07_Clips_30s',
    combined: '08_Combined',
    exports: '09_Exports'
  },
  
  getPath(type, filename) {
    return `${this.base}/${this.structure[type] || '00_Other'}/${filename}`;
  }
};

// ═══════════════════════════════════════════════════════════
// INITIALIZATION
// ═══════════════════════════════════════════════════════════

loadDB().then(async () => {
  await QuotaTracker.load();
  console.log('[GeminiGen Auto Flow Pro] Initialized');
  QuotaTracker.broadcast();
});