// ═══════════════════════════════════════════════════════════
// GEMINIGEN AUTO FLOW PRO - Background Service Worker v2.0
// ═══════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════
// DATABASE - Memory System (come Whisk)
// ═══════════════════════════════════════════════════════════

const DB = {
  characters: {},
  environments: {},
  scripts: {},          // Copioni completi
  projects: {},         // Progetti di lavoro
  activeProject: null,
  autoGeneratedCharacter: null,  // Personaggio auto-generato
  autoGeneratedEnvironment: null // Ambiente auto-generato
};

// ═══════════════════════════════════════════════════════════
// AUTO GENERATE FUNCTION
// ═══════════════════════════════════════════════════════════

function autoGenerateFromScript(scenes) {
  const result = {
    character: null,
    environment: null,
    autoGenerated: false
  };
  
  // Genera personaggio se non presente
  if (!DB.autoGeneratedCharacter) {
    result.character = AutoGenerator.generateCharacterFromScript(scenes);
    DB.autoGeneratedCharacter = result.character;
    DB.characters[result.character.id] = result.character;
  } else {
    result.character = DB.autoGeneratedCharacter;
  }
  
  // Genera ambiente se non presente
  if (!DB.autoGeneratedEnvironment) {
    result.environment = AutoGenerator.generateEnvironmentFromScript(scenes);
    DB.autoGeneratedEnvironment = result.environment;
    DB.environments[result.environment.id] = result.environment;
  } else {
    result.environment = DB.autoGeneratedEnvironment;
  }
  
  result.autoGenerated = true;
  
  // Salva
  saveDB();
  
  console.log('[AutoGenerate] Character:', result.character.name);
  console.log('[AutoGenerate] Environment:', result.environment.name);
  
  return { success: true, ...result };
}

// Reset auto-generated (quando utente seleziona manualmente)
function resetAutoGenerated() {
  DB.autoGeneratedCharacter = null;
  DB.autoGeneratedEnvironment = null;
  saveDB();
}

// ═══════════════════════════════════════════════════════════
// SCRIPT PARSER - Suddivide copione in scene/prompt
// ═══════════════════════════════════════════════════════════

const ScriptParser = {
  // Pattern da ESCLUDERE (rumore)
  noisePatterns: [
    // Header/Footer comuni
    /^\s*✅.*PROMPT/i,
    /^\s*✅\s*TUTTI\s*I\s*\d+\s*PROMPT\s*COMPLETATI/i,
    /^\s*✅\s*CONTINUAZIONE/i,
    /^\s*✅\s*ECC.*/i,
    /^\s*\[DNA.*\]/i,
    /^\s*DNA\s+APPLICATO/i,
    /^\s*Vuoi\s+che\s+ti\s+.*/i,
    /^\s*Ogni\s+\d+\s+prompt/i,
    /^\s*---\s*$/,
    
    // DNA ripetuto
    /Ridley Scott cinematic documentary/i,
    /heavy film grain/i,
    /anamorphic lens/i,
    /warm sunset color grading/i,
    /volumetric god rays/i,
    /dust particles/i,
    /photorealistic 4K/i,
    
    // Strutture fisse
    /Crea un video cinematico di esattamente \d+ secondi/i,
    /^\s*Descrizione visiva:\s*$/i,
    /^\s*Voiceover:\s*$/i,
    /^\s*Suono di sottofondo:\s*$/i,
    /^\s*DNA\s*:\s*$/i,
    
    // Batch headers
    /BATCH\s*\d+\s*\(\s*\d+-\d+\s*\)/i,
    /^\s*BATCH\s*\d+/i,
    
    // Numerazione prompt
    /PROMPT\s+\d+\s*\n/i,
    
    // Footer
    /Prodotto da Space Archive/i,
    /Iscriviti per altri/i,
    /Grazie per aver guardato/i,
  ],
  
  // Pattern che indicano nuova scena/prompt
  promptPatterns: [
    /^PROMPT\s+(\d+)/i,
    /^\[PROMPT\s+(\d+)\]/i,
    /^\d+\s*[\.\)]\s*(.+)/,
    /^Clip\s+(\d+)/i,
    /^SCENA\s+(\d+)/i,
  ],
  
  // Estrai solo la descrizione visiva (o contenuto significativo)
  extractVisualDescription(text) {
    // Cerca "Descrizione visiva:" e prendi tutto dopo
    const descMatch = text.match(/Descrizione visiva:\s*(.+?)(?=\s*(?:Voiceover|Suono|$))/is);
    if (descMatch) {
      return descMatch[1].trim();
    }
    
    // Altrimenti prendi tutto dopo il DNA (se presente)
    const dnaMatch = text.match(/DNA[\s:]*[^\n]*\n(.+)/is);
    if (dnaMatch) {
      let cleaned = dnaMatch[1];
      // Rimuovi voiceover e suono
      cleaned = cleaned.replace(/Voiceover:.*?(?=\n|$)/gis, '');
      cleaned = cleaned.replace(/Suono di sottofondo:.*?(?=\n|$)/gis, '');
      return cleaned.trim();
    }
    
    // Altrimenti prendi tutto
    return text;
  },
  
  // Pulisci una linea dal rumore
  cleanLine(line) {
    let cleaned = line.trim();
    
    // Rimuovi prefissi come "PROMPT 001"
    cleaned = cleaned.replace(/^PROMPT\s+\d+\s*/i, '');
    cleaned = cleaned.replace(/^\d+\s*[\.\)]\s*/, '');
    cleaned = cleaned.replace(/^-\s*/, '');
    
    // Rimuovi etichette come "DNA:", "Descrizione visiva:", ecc.
    cleaned = cleaned.replace(/^(DNA|Descrizione visiva|Voiceover|Suono di sottofondo)\s*:\s*/gi, '');
    
    return cleaned;
  },
  
  // Verifica se è una linea di rumore
  isNoise(line) {
    const trimmed = line.trim();
    
    // Linee vuote non sono rumore
    if (!trimmed) return false;
    
    // Check contro tutti i pattern di rumore
    for (const pattern of this.noisePatterns) {
      if (pattern.test(trimmed)) return true;
    }
    
    // Linea troppo corta
    if (trimmed.length < 5) return true;
    
    // Solo numeri/punteggiatura
    if (/^[0-9\s\.\,\-\(\)]+$/.test(trimmed)) return true;
    
    return false;
  },
  
  // Parse copione completo - estrae VISIVA + VOCE + SUONO
  parseScript(text) {
    const scenes = [];
    
    // Pulisci il testo base
    let cleanText = text;
    
    // Rimuovi header comuni all'inizio
    cleanText = cleanText.replace(/^[\s\S]*?(?=PROMPT\s+\d+|^\d+\s*[\.\)]|BATCH\s*\d)/i, '');
    
    // Rimuovi footer comuni alla fine  
    cleanText = cleanText.replace(/(Prodotto da|Vuoi che|Raggruppa|Iscriviti|z-ai)[\s\S]*$/i, '');
    
    // Suddividi per PROMPT (ogni PROMPT = una scena)
    const promptMatches = cleanText.matchAll(/PROMPT\s+(\d+)(?:\s*\n|\s*)([\s\S]*?)(?=(?:\s*PROMPT\s+\d+)|$)/gi);
    
    for (const match of promptMatches) {
      const promptNumStr = match[1];
      const promptContent = match[2];
      
      // Estrai tutti i campi
      const fields = this.extractAllFields(promptContent);
      
      // Usa il NUMERO REALE dal testo (001, 002, ecc.)
      const realPromptNum = parseInt(promptNumStr, 10);
      
      if (fields.visualDescription.length > 10 || fields.voiceover.length > 5) {
        scenes.push({
          index: scenes.length,  // Indice sequenziale
          title: `Prompt ${realPromptNum}`,  // Numero reale nel titolo
          visualDescription: fields.visualDescription,
          voiceover: fields.voiceover,
          audio: fields.audio,
          duration: 6,
          promptNumber: realPromptNum  // Numero reale
        });
      }
    }
    
    // Se non abbiamo trovato PROMPT, prova metodo alternativo
    if (scenes.length === 0) {
      return this.parseScriptAlternative(cleanText);
    }
    
    console.log(`[ScriptParser] Parsed ${scenes.length} prompts with full fields`);
    return scenes;
  },
  
  // Estrai tutti i campi da un prompt
  extractAllFields(content) {
    const result = {
      visualDescription: '',
      voiceover: '',
      audio: ''
    };
    
    // Estrai Descrizione visiva
    const visualMatch = content.match(/Descrizione visiva:\s*(.+?)(?=\s*(?:Voiceover|Suono|$))/is);
    if (visualMatch) {
      result.visualDescription = visualMatch[1].trim();
    }
    
    // Estrai Voiceover
    const voiceMatch = content.match(/Voiceover:\s*(.+?)(?=\s*(?:Suono|$))/is);
    if (voiceMatch) {
      result.voiceover = voiceMatch[1].trim();
    }
    
    // Estrai Suono di sottofondo
    const audioMatch = content.match(/Suono di sottofondo:\s*(.+?)(?=\s*(?:$))/is);
    if (audioMatch) {
      result.audio = audioMatch[1].trim();
    }
    
    // Se non abbiamo estratto niente, prova a pulire tutto
    if (!result.visualDescription && !result.voiceover) {
      // Rimuovi DNA e prendi il resto
      let cleaned = content
        .replace(/DNA[\s:]*[^\n]*\n/gi, '')
        .replace(/Crea un video cinematico.*?\n/gi, '');
      
      // Separa per linea
      const lines = cleaned.split('\n').filter(l => l.trim());
      
      for (const line of lines) {
        const trimmed = line.trim();
        
        if (trimmed.toLowerCase().startsWith('voiceover:')) {
          result.voiceover = trimmed.replace(/^voiceover:\s*/i, '').trim();
        } else if (trimmed.toLowerCase().startsWith('suono')) {
          result.audio = trimmed.replace(/^suono[\s\w]*:\s*/i, '').trim();
        } else if (trimmed.length > 10 && !this.isNoise(trimmed)) {
          result.visualDescription = trimmed;
        }
      }
    }
    
    return result;
  },
  
  // Metodo alternativo: ogni riga non vuota = prompt
  parseScriptAlternative(text) {
    const scenes = [];
    const lines = text.split('\n');
    
    let currentScene = null;
    let promptNum = 1;
    
    for (const line of lines) {
      const trimmed = line.trim();
      
      // Salta se è rumore
      if (this.isNoise(trimmed)) continue;
      
      // Pulisci la linea
      const cleaned = this.cleanLine(trimmed);
      if (cleaned.length < 10) continue;
      
      // Nuovo prompt se c'è separatore
      if (/^[-_]{3,}$/.test(trimmed) || /^(BATCH|PROMPT|Clip|SCENA)\s*\d+/i.test(trimmed)) {
        // Salva quello precedente
        if (currentScene && currentScene.visualDescription) {
          scenes.push(currentScene);
          promptNum++;
        }
        currentScene = {
          index: scenes.length,
          title: `Prompt ${promptNum}`,
          visualDescription: '',
          voiceover: '',
          audio: '',
          duration: 6,
          promptNumber: promptNum,
          character: null,
          environment: null
        };
        continue;
      }
      
      // Classifica la linea
      if (!currentScene) {
        currentScene = {
          index: scenes.length,
          title: `Prompt ${promptNum}`,
          visualDescription: '',
          voiceover: '',
          audio: '',
          duration: 6,
          promptNumber: promptNum,
          character: null,
          environment: null
        };
      }
      
      if (trimmed.toLowerCase().startsWith('voiceover:')) {
        currentScene.voiceover = trimmed.replace(/^voiceover:\s*/i, '').trim();
      } else if (trimmed.toLowerCase().startsWith('suono')) {
        currentScene.audio = trimmed.replace(/^suono[\s\w]*:\s*/i, '').trim();
      } else {
        currentScene.visualDescription = cleaned;
      }
    }
    
    // Salva l'ultimo
    if (currentScene && currentScene.visualDescription) {
      scenes.push(currentScene);
    }
    
    console.log(`[ScriptParser] Alt method: ${scenes.length} prompts with full fields`);
    return scenes;
  },
  
  // Combina scene per clip lunga
  combineForLongClip(scenes, targetDuration) {
    const combined = [];
    let currentGroup = [];
    let currentDuration = 0;
    const clipsPerGroup = Math.ceil(targetDuration / 6);
    
    for (const scene of scenes) {
      currentGroup.push(scene);
      
      if (currentGroup.length >= clipsPerGroup) {
        combined.push({
          scenes: [...currentGroup],
          prompt: this.buildCombinedPrompt(currentGroup),
          duration: Math.min(targetDuration, currentGroup.length * 6)
        });
        currentGroup = [];
      }
    }
    
    // Aggiungi gruppi rimanenti
    if (currentGroup.length > 0) {
      combined.push({
        scenes: [...currentGroup],
        prompt: this.buildCombinedPrompt(currentGroup),
        duration: currentGroup.length * 6
      });
    }
    
    return combined;
  },
  
  // Costruisce prompt combinato da scene
  buildCombinedPrompt(scenes) {
    return scenes.map(s => {
      const titlePart = s.title ? `[${s.title}] ` : '';
      return titlePart + s.prompts.join(' ');
    }).join(' | ');
  }
};

// ═══════════════════════════════════════════════════════════
// CLIP INTELLIGENCE ENGINE
// ═══════════════════════════════════════════════════════════

const ClipEngine = {
  // Formati clip supportati
  formats: {
    micro: 4,    // 4 secondi
    short: 6,    // 6 secondi
    medium: 8,   // 8 secondi
    long: 15,    // 15 secondi
    full: 30     // 30 secondi
  },
  
  // Decisione automatica clip
  decideClipFormat(sceneCount, targetDuration) {
    // Se target è 30s e abbiamo 5 scene da 6s, combiniamo
    if (targetDuration === 30 && sceneCount > 1) {
      const groups = Math.ceil(sceneCount / 5);
      return {
        clipDuration: 6,
        scenesPerClip: Math.ceil(sceneCount / groups),
        totalClips: groups,
        mode: 'combined_30s'
      };
    }
    
    // Altrimenti clip singola
    return {
      clipDuration: targetDuration,
      scenesPerClip: 1,
      totalClips: sceneCount,
      mode: 'single'
    };
  },
  
  // Genera sequenza di clip da copione
  generateClipSequence(scenes, options = {}) {
    const { targetDuration = 6, autoCombine = true } = options;
    
    // Se autoCombine e target è lungo
    if (autoCombine && targetDuration >= 15 && scenes.length > 1) {
      return this.combineForLongClip(scenes, targetDuration);
    }
    
    // Altrimenti una clip per scena
    return scenes.map((scene, i) => ({
      index: i,
      scene: scene,
      prompt: scene.prompts.join(' '),
      duration: Math.min(targetDuration, scene.duration || 6),
      startTime: i * (scene.duration || 6)
    }));
  },
  
  // Combina scene per clip lunga
  combineForLongClip(scenes, targetDuration) {
    const clips = [];
    const scenesPerClip = Math.ceil(scenes.length / Math.ceil(targetDuration / 6));
    
    for (let i = 0; i < scenes.length; i += scenesPerClip) {
      const group = scenes.slice(i, i + scenesPerClip);
      clips.push({
        index: clips.length,
        scenes: group,
        prompt: group.map(s => `[${s.title || 'S' + s.index}] ${s.prompts.join(' ')}`).join(' '),
        duration: Math.min(targetDuration, group.length * 6),
        sceneRange: `${i + 1}-${Math.min(i + scenesPerClip, scenes.length)}`
      });
    }
    
    return clips;
  }
};

// ═══════════════════════════════════════════════════════════
// AUTO GENERATOR - Genera personaggi/ambienti se mancanti
// ═══════════════════════════════════════════════════════════

const AutoGenerator = {
  // Genera personaggio da copione/scene
  generateCharacterFromScript(scenes) {
    // Analizza il copione per identificare personaggi
    const allText = scenes.map(s => s.title + ' ' + s.prompts.join(' ')).join(' ');
    
    // Pattern comuni per identificare personaggi
    const patterns = [
      /(?:un|uomo|una|donna|bambino|bambina|ragazzo|ragazza|personaggio|protagonista|antagonista|eroe|villano)\s*(?:di\s+)?([^,\.]+)/i,
      /([A-Z][a-z]+)\s+(?:entra|esce|appare|scompare|cammina|corre|grida|parla)/,
      /([A-Z][a-z]+):\s*(.+)/,
      /(?:il|l'|la)\s+([a-z]+)\s+(?:è|ha|sembra)/i
    ];
    
    let characterName = null;
    let characterDesc = null;
    
    for (const pattern of patterns) {
      const match = allText.match(pattern);
      if (match) {
        characterName = match[1] || match[2] || 'Protagonista';
        characterDesc = this.extractCharacterDescription(allText, characterName);
        break;
      }
    }
    
    if (!characterName) {
      // Genera personaggio generico basato sul tono del copione
      const tone = this.detectTone(scenes);
      characterName = tone.defaultCharacter;
      characterDesc = tone.defaultDesc;
    }
    
    return {
      id: 'auto_char_' + Date.now(),
      name: characterName,
      description: characterDesc,
      prompt: this.buildCharacterPrompt(characterName, characterDesc),
      autoGenerated: true,
      createdAt: Date.now()
    };
  },
  
  // Genera ambiente da copione/scene
  generateEnvironmentFromScript(scenes) {
    const allText = scenes.map(s => s.title + ' ' + s.prompts.join(' ')).join(' ');
    
    // Pattern per ambienti
    const patterns = [
      /(?:in|nel|alla|nella)\s+([^,\.]+)/i,
      /(?:dentro|dentro\s+a)\s+([^,\.]+)/i,
      /(?:luogo|posto|location|scenario):\s*([^,\.]+)/i,
      /(?:accade|avviene|svolge)\s+(?:in|al)\s+([^,\.]+)/i
    ];
    
    let envName = null;
    let envDesc = null;
    let envMood = 'neutral';
    let envLighting = 'natural';
    
    for (const pattern of patterns) {
      const match = allText.match(pattern);
      if (match && match[1].length > 2) {
        envName = match[1].trim();
        envDesc = this.extractEnvironmentDescription(allText, envName);
        break;
      }
    }
    
    if (!envName) {
      const tone = this.detectTone(scenes);
      envName = tone.defaultEnvironment;
      envDesc = tone.defaultEnvDesc;
      envMood = tone.mood;
      envLighting = tone.lighting;
    }
    
    return {
      id: 'auto_env_' + Date.now(),
      name: envName,
      description: envDesc,
      mood: envMood,
      lighting: envLighting,
      autoGenerated: true,
      createdAt: Date.now()
    };
  },
  
  // Estrai descrizione personaggio
  extractCharacterDescription(text, name) {
    const sentences = text.split(/[.!]/);
    for (const sentence of sentences) {
      if (sentence.toLowerCase().includes(name.toLowerCase())) {
        // Estrai descrizione dalla frase
        const desc = sentence.trim();
        if (desc.length > 10 && desc.length < 200) {
          return desc;
        }
      }
    }
    return this.generateGenericDescription(text);
  },
  
  // Genera descrizione generica
  generateGenericDescription(text) {
    const hasDark = /dark|notte|oscur|tenebr/i.test(text);
    const hasAction = /esplos|azion|cors|combatt/i.test(text);
    const hasSciFi = /spaz|alien|robot|tecnolog/i.test(text);
    
    if (hasSciFi) return 'A mysterious figure with futuristic attire';
    if (hasAction) return 'An athletic person in dynamic pose';
    if (hasDark) return 'A shadowy silhouette in dark atmosphere';
    return 'A person with cinematic presence';
  },
  
  // Estrai descrizione ambiente
  extractEnvironmentDescription(text, name) {
    const sentences = text.split(/[.!]/);
    for (const sentence of sentences) {
      if (sentence.toLowerCase().includes(name.toLowerCase())) {
        const desc = sentence.trim();
        if (desc.length > 10 && desc.length < 200) {
          return desc;
        }
      }
    }
    return `Location: ${name}. Cinematic setting.`;
  },
  
  // Costruisci prompt personaggio
  buildCharacterPrompt(name, description) {
    return `${name}. ${description}. Cinematic style, detailed, high quality rendering.`;
  },
  
  // Rileva tono del copione
  detectTone(scenes) {
    const allText = scenes.map(s => s.prompts.join(' ')).join(' ').toLowerCase();
    
    if (/alien|spaz|galax|rocket|astro/i.test(allText)) {
      return {
        mood: 'mysterious',
        lighting: 'dramatic neon',
        defaultCharacter: 'Astronaut',
        defaultDesc: 'A space explorer in futuristic suit',
        defaultEnvironment: 'Space Station',
        defaultEnvDesc: 'Futuristic space station with neon lights and control panels'
      };
    }
    
    if (/uffici|azienda|reunion|computer/i.test(allText)) {
      return {
        mood: 'professional',
        lighting: 'office fluorescent',
        defaultCharacter: 'Business Person',
        defaultDesc: 'A professional in smart casual attire',
        defaultEnvironment: 'Office',
        defaultEnvDesc: 'Modern office with desks and computers'
      };
    }
    
    if (/foresta|alber|natura|selvag/i.test(allText)) {
      return {
        mood: 'serene',
        lighting: 'natural sunlight',
        defaultCharacter: 'Wanderer',
        defaultDesc: 'A traveler in outdoor clothing',
        defaultEnvironment: 'Forest',
        defaultEnvDesc: 'Dense forest with sunlight filtering through trees'
      };
    }
    
    // Default cinematic
    return {
      mood: 'dramatic',
      lighting: 'cinematic',
      defaultCharacter: 'Mysterious Figure',
      defaultDesc: 'A silhouetted person in dramatic lighting',
      defaultEnvironment: 'Cinematic Scene',
      defaultEnvDesc: 'Dramatic setting with cinematic lighting and atmosphere'
    };
  }
};

// ═══════════════════════════════════════════════════════════
// GENERATIONS TRACKER - Quote e limiti
// ═══════════════════════════════════════════════════════════

const QuotaTracker = {
  quota: {
    daily: { total: 0, used: 0, remaining: 0 },
    monthly: { total: 0, used: 0, remaining: 0 },
    unlimited: true  // Di default è ILLIMITATO finché non rileva diversamente
  },
  
  update(data) {
    this.quota = { ...this.quota, ...data };
    this.save();
    this.broadcast();
  },
  
  recordGeneration(success) {
    if (!this.quota.unlimited) {
      this.quota.daily.used++;
      this.quota.monthly.used++;
      this.quota.daily.remaining = Math.max(0, this.quota.daily.total - this.quota.daily.used);
      this.quota.monthly.remaining = Math.max(0, this.quota.monthly.total - this.quota.monthly.used);
    }
    this.save();
    this.broadcast();
  },
  
  canGenerate() {
    if (this.quota.unlimited) return { allowed: true };
    return {
      allowed: this.quota.daily.remaining > 0,
      remaining: this.quota.daily.remaining
    };
  },
  
  getDisplay() {
    if (this.quota.unlimited) {
      return { status: 'unlimited', daily: '∞', monthly: '∞', remaining: '∞' };
    }
    return {
      status: this.quota.daily.remaining > 0 ? 'active' : 'depleted',
      daily: { used: this.quota.daily.used, total: this.quota.daily.total },
      monthly: { used: this.quota.monthly.used, total: this.quota.monthly.total },
      remaining: this.quota.daily.remaining
    };
  },
  
  async save() {
    await chrome.storage.local.set({ quota: this.quota });
  },
  
  async load() {
    const result = await chrome.storage.local.get('quota');
    if (result.quota) {
      this.quota = result.quota;
    } else {
      // Nessuna quota salvata → usa unlimited
      this.quota.unlimited = true;
    }
  },
  
  broadcast() {
    chrome.runtime.sendMessage({ type: 'QUOTA_UPDATE', quota: this.getDisplay() }).catch(() => {});
  }
};

// ═══════════════════════════════════════════════════════════
// AUTO FLOW STATE
// ═══════════════════════════════════════════════════════════

const AutoFlow = {
  isRunning: false,
  isPaused: false,
  currentClipIndex: 0,
  clips: [],
  config: {
    clipDuration: 6,
    autoCombine: true,
    delayBetween: 2000,
    contextMode: 'character' // 'character' | 'environment' | 'both'
  },
  
  start(clips, config = {}) {
    this.clips = clips;
    this.config = { ...this.config, ...config };
    this.isRunning = true;
    this.isPaused = false;
    this.currentClipIndex = 0;
    this.broadcast();
  },
  
  pause() {
    this.isPaused = true;
    this.broadcast();
  },
  
  resume() {
    this.isPaused = false;
    this.broadcast();
  },
  
  stop() {
    this.isRunning = false;
    this.isPaused = false;
    this.broadcast();
  },
  
  nextClip() {
    this.currentClipIndex++;
    if (this.currentClipIndex >= this.clips.length) {
      this.stop();
    }
    this.broadcast();
  },
  
  getCurrentClip() {
    return this.clips[this.currentClipIndex];
  },
  
  getProgress() {
    return {
      current: this.currentClipIndex + 1,
      total: this.clips.length,
      percentage: Math.round(((this.currentClipIndex + 1) / this.clips.length) * 100),
      clip: this.getCurrentClip()
    };
  },
  
  broadcast() {
    chrome.runtime.sendMessage({ 
      type: 'FLOW_UPDATE', 
      flow: { isRunning: this.isRunning, isPaused: this.isPaused },
      progress: this.getProgress()
    }).catch(() => {});
  }
};

// ═══════════════════════════════════════════════════════════
// MESSAGE HANDLER
// ═══════════════════════════════════════════════════════════

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  console.log('[Background] Message:', msg.type);
  
  switch (msg.type) {
    // === CHARACTER ===
    case 'SAVE_CHARACTER':
      saveCharacter(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'GET_CHARACTERS':
      sendResponse({ success: true, characters: DB.characters });
      return true;
      
    case 'DELETE_CHARACTER':
      deleteCharacter(msg.id).then(r => sendResponse(r));
      return true;
      
    // === ENVIRONMENT ===
    case 'SAVE_ENVIRONMENT':
      saveEnvironment(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'GET_ENVIRONMENTS':
      sendResponse({ success: true, environments: DB.environments });
      return true;
      
    case 'DELETE_ENVIRONMENT':
      deleteEnvironment(msg.id).then(r => sendResponse(r));
      return true;
      
    // === SCRIPT ===
    case 'LOAD_SCRIPT':
      loadScript(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'PARSE_SCRIPT':
      const scenes = ScriptParser.parseScript(msg.text);
      sendResponse({ success: true, scenes });
      return true;
      
    case 'GENERATE_CLIP_SEQUENCE':
      const clips = ClipEngine.generateClipSequence(msg.scenes, msg.options);
      sendResponse({ success: true, clips });
      return true;
      
    case 'SAVE_SCRIPT':
      saveScript(msg.data).then(r => sendResponse(r));
      return true;
      
    case 'GET_SCRIPTS':
      sendResponse({ success: true, scripts: DB.scripts });
      return true;
      
    // === AUTO FLOW ===
    case 'START_FLOW':
      AutoFlow.start(msg.clips, msg.config);
      sendResponse({ success: true });
      return true;
      
    case 'PAUSE_FLOW':
      AutoFlow.pause();
      sendResponse({ success: true });
      return true;
      
    case 'RESUME_FLOW':
      AutoFlow.resume();
      sendResponse({ success: true });
      return true;
      
    case 'STOP_FLOW':
      AutoFlow.stop();
      sendResponse({ success: true });
      return true;
      
    case 'GET_FLOW_STATUS':
      sendResponse({ success: true, flow: AutoFlow, progress: AutoFlow.getProgress() });
      return true;
      
    case 'NEXT_CLIP':
      AutoFlow.nextClip();
      sendResponse({ success: true, clip: AutoFlow.getCurrentClip() });
      return true;
      
    // === QUOTA ===
    case 'UPDATE_QUOTA':
      QuotaTracker.update(msg.data);
      sendResponse({ success: true });
      return true;
      
    case 'GET_QUOTA':
      sendResponse({ success: true, quota: QuotaTracker.getDisplay() });
      return true;
      
    case 'RECORD_GENERATION':
      QuotaTracker.recordGeneration(msg.success);
      sendResponse({ success: true, canGenerate: QuotaTracker.canGenerate() });
      return true;
      
    // === CONFIG ===
    case 'GET_CONFIG':
      sendResponse({ success: true, config: AutoFlow.config });
      return true;
      
    case 'SET_CONFIG':
      AutoFlow.config = { ...AutoFlow.config, ...msg.config };
      saveConfig();
      sendResponse({ success: true });
      return true;
      
    // === AUTO GENERATE ===
    case 'AUTO_GENERATE_MISSING':
      const result = autoGenerateFromScript(msg.scenes);
      sendResponse(result);
      return true;
      
    case 'GET_AUTO_GENERATED':
      sendResponse({ 
        success: true, 
        autoCharacter: DB.autoGeneratedCharacter,
        autoEnvironment: DB.autoGeneratedEnvironment 
      });
      return true;
      
    default:
      sendResponse({ success: false, error: 'Unknown type' });
  }
});

// ═══════════════════════════════════════════════════════════
// CRUD OPERATIONS
// ═══════════════════════════════════════════════════════════

async function saveCharacter(data) {
  const id = data.id || 'char_' + Date.now();
  DB.characters[id] = { id, ...data, createdAt: Date.now(), usageCount: 0 };
  await saveDB();
  return { success: true, id };
}

async function deleteCharacter(id) {
  delete DB.characters[id];
  await saveDB();
  return { success: true };
}

async function saveEnvironment(data) {
  const id = data.id || 'env_' + Date.now();
  DB.environments[id] = { id, ...data, createdAt: Date.now(), usageCount: 0 };
  await saveDB();
  return { success: true, id };
}

async function deleteEnvironment(id) {
  delete DB.environments[id];
  await saveDB();
  return { success: true };
}

async function saveScript(data) {
  const id = data.id || 'script_' + Date.now();
  const parsed = ScriptParser.parseScript(data.text);
  DB.scripts[id] = { id, name: data.name, text: data.text, scenes: parsed, createdAt: Date.now() };
  await saveDB();
  return { success: true, id, scenes: parsed };
}

async function loadScript(id) {
  const script = DB.scripts[id];
  if (!script) return { success: false, error: 'Not found' };
  return { success: true, script, scenes: script.scenes };
}

async function saveConfig() {
  await chrome.storage.local.set({ 
    config: AutoFlow.config,
    db: DB
  });
}

async function saveDB() {
  await chrome.storage.local.set({ db: DB });
}

async function loadDB() {
  const result = await chrome.storage.local.get(['db', 'quota', 'config']);
  if (result.db) {
    DB.characters = result.db.characters || {};
    DB.environments = result.db.environments || {};
    DB.scripts = result.db.scripts || {};
    DB.projects = result.db.projects || {};
  }
  if (result.quota) QuotaTracker.quota = result.quota;
  if (result.config) AutoFlow.config = result.config;
}

// ═══════════════════════════════════════════════════════════
// OUTPUT FOLDER SYSTEM
// ═══════════════════════════════════════════════════════════

const OutputFolder = {
  base: 'GeminiGen-AutoFlow',
  
  structure: {
    scripts: '01_Scripts',
    characters: '02_Characters',
    environments: '03_Environments',
    clips_6s: '04_Clips_6s',
    clips_8s: '05_Clips_8s',
    clips_15s: '06_Clips_15s',
    clips_30s: '07_Clips_30s',
    combined: '08_Combined',
    exports: '09_Exports'
  },
  
  getPath(type, filename) {
    return `${this.base}/${this.structure[type] || '00_Other'}/${filename}`;
  }
};

// ═══════════════════════════════════════════════════════════
// INITIALIZATION
// ═══════════════════════════════════════════════════════════

loadDB().then(async () => {
  await QuotaTracker.load();
  console.log('[GeminiGen Auto Flow Pro] Initialized');
  QuotaTracker.broadcast();
});